### PR TITLE
Cssconcat

### PR DESCRIPTION
**Pull request by IlyaRucavitcyn**
[Gulp css concat](https://www.npmjs.com/package/gulp-concat-css/) is installed trough out the devenv. "gulp concatcss" task is defined in [gulpfile.js](https://github.com/IlyaRucavitcyn/vanga.by/blob/cssconcat/gulpfile.js). A new folder [css_tmp](https://github.com/IlyaRucavitcyn/vanga.by/tree/cssconcat/css_tmp) is created to collect all intermediate *.css files there. The final concatenated *.css file is being created in [css folder](https://github.com/IlyaRucavitcyn/vanga.by/tree/cssconcat/css). It is connected to the [index.html](https://github.com/IlyaRucavitcyn/vanga.by/blob/cssconcat/index.html) via <link> tag.

The latest webview can be found [here](http://ilyarucavitcyn.github.io/vanga.by/).

### CODE REVIEW

**Comment by shemerey** [comment]
By convention result files going to dir `dist`, It's also a bad idea to use `tmp` as a part of name for source folder, some scripts or even human beings will remove this folder without any doubts.

**Comment by shemerey** [comment]
It's better to put final result into `.gitignore` and build this file each time you deploy your code. We going to make this as part of our deployment process, in future issues

**Comment by IlyaRucavitcyn** [comment]
- [x] "css_tmp" is renamed into "src", "css" is added to .gitignore

**Comment by shemerey** [comment]
`css/bundle.css` still in the repo, plz remove it

**Comment by IlyaRucavitcyn** [comment]
Finally removed it seems to me ;)

**Pull request merged**
