### PR TITLE
Burger icon

### PR DESCRIPTION
**Pull request by IlyaRucavitcyn**
Concerning burger Icon issue: Clean white sidebar appears after pushing burger icon. to hide it - click on the sidebar. It is possible with the help of the file burgerIcon.js.  Plz check here: http://ilyarucavitcyn.github.io/vanga.by

Concerning artefacts, appearing when changing window, the problem is solved using svg images. The result can be checked here: http://ilyarucavitcyn.github.io/vanga.by

### CODE REVIEW

**Comment by shemerey** [comment]
@IlyaRucavitcyn you have to avoid spaces in file names `img/currency buttons-06.svg` will be treated incorrectly depends on operation system some times, to avoid mysterious bugs plz remove all spaces and ambiguous characters.

BTW don't use Cyrillic and UTF-8 chars as well, stick to en + numbers

**Comment by shemerey** [comment]
looks like `img/ethalone.png` is the wrong file to use it as ethalone

**Comment by shemerey** [comment]
@IlyaRucavitcyn BTW I saw some `CamelCase` in your css selectors, did you do it for purpose or accidentally ?

I've found some flame about it here http://stackoverflow.com/questions/12533926/are-class-names-in-css-selectors-case-sensitive

In general we don't use case sensitive names for css selectors. 

> Names should be lowercase, using a dash - as a separator in a multi-word class > names. It's clear, readable and distinguish CSS from underscore case and camel case naming. 

There are many css style guides over there for instance https://gist.github.com/bobbygrace/9e961e8982f42eb91b80

**Comment by IlyaRucavitcyn** [comment]
- [x] All spaces, UTF-8 and Cirillyc symbols and ambiguous characters are deleted. I've also cleaned up the branch from files i don't use or plan to use later. As most of the svg images are inserted through out the xml in the DOM i only need a few in my folder.
- [x] Ethalon file is deleted as I don't really need, it was nothing but rubbish
-[ ] Working on CSS selectors styling

**Comment by IlyaRucavitcyn** [comment]
@shemerey 
- [x] Base CSS-selectors styling is made. Camelcases are replaced with usual words, separated with "-". Find the latest files 2fff946d03c805c61d2d6178d2a5c0ade939db32 (sorry if there is some mess with the links, I am still new on github :)

**Comment by shemerey** [comment]
LGTM :shipit:

**Pull request merged**
